apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-Dor
spec:
  containers:
  - image: redis:alpine
    name: redis-alpine
    volumeMounts:
    - mountPath: /data/redis
      name: data-redis-volume
  volumes:
  - name: data-redis-volume
    emptyDir: []
