apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
spec:
  containers:
  - name: nginx-resolver
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
  labels:
    app: nginx-resolver
spec:
  selector:
    run: nginx-resolver
  type: ClusterIP
  ports:          
    - name: nginx-resolver
      protocol: TCP
      port: 80
      targetPort: 80




kubectl run test-ns --image=busybox:1.28 -it --restart=Never -- nslookup nginx-resolver-service
