apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: nginx-critical
spec:
  containers:
  - name: nginx-critical
    image: nginx   
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/role: node
