apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: alpha
    image: nginx
    env:
    - name: alpha_env
      value: "alpha-env"
  - name: beta
    image: busybox
    command: ["sleep","4800"]
    env:
    - name: beta_env
      value: "beta-env"
